module.exports = {
  testEnvironment: "node",
  testMatch: ["**/tests/**/*.test.js"],
  collectCoverageFrom: [
    "lib/**/*.js",
    "!lib/**/*-backup.js",
    "!lib/**/*-broken.js",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov"],
  modulePathIgnorePatterns: [
    "<rootDir>/node_modules/",
    "<rootDir>/dist/",
    "<rootDir>/coverage/",
    "<rootDir>/coclaw-backup-20260408-181211/",
    "<rootDir>/.cache/",
    "<rootDir>/.config/",
    "<rootDir>/.coclaw/",
    "<rootDir>/.openclaw/",
    "<rootDir>/.roter/",
    "<rootDir>/CSIS/",
    "<rootDir>/backroom/",
    "<rootDir>/backroom-mod/",
    "<rootDir>/clash-verge-fixed/",
    "<rootDir>/cli-tool/",
    "<rootDir>/duky/",
    "<rootDir>/examples/",
    "<rootDir>/furtheraether/",
    "<rootDir>/internet/",
    "<rootDir>/jdk17/",
    "<rootDir>/memory/",
    "<rootDir>/mods/",
    "<rootDir>/moner/",
    "<rootDir>/openclaw-mom/",
    "<rootDir>/openclaw-mom-workspace/",
    "<rootDir>/openloth/",
    "<rootDir>/planer/",
    "<rootDir>/skills-searching/",
    "<rootDir>/supermanger/",
    "<rootDir>/undercrab/",
    "<rootDir>/worker/",
    "<rootDir>/workspace/",
  ],
};
